### Create a new poll
POST http://localhost:8888/polls
Content-Type: application/json

{
  "name": "Favorite Programming Language",
  "description": "Vote for your favorite programming language",
  "options": [
    {
      "name": "Go",
      "description": "The Go Programming Language"
    },
    {
      "name": "Python",
      "description": "The Python Programming Language"
    },
    {
      "name": "JavaScript",
      "description": "The JavaScript Programming Language"
    }
  ]
}

### Vote
PUT http://localhost:4000/polls/2/options/4/users/1
Content-Type: application/json


### Subscribe for results
#curl -i -N -H "Upgrade: websocket" -H "Connection: Upgrade" -H "Sec-WebSocket-Key: $(openssl rand -base64 16)" -H "Sec-WebSocket-Version: 13" http://localhost:4000/ws/polls/1